name: 'release'

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - id: version
        name: Determine next version
        uses: conventional-actions/next-version@e48c1275d221bd29e2c08f8856b91695c0a72db1 # v1.1.6
      - name: Update package.json version
        uses: conventional-actions/write-version@77c6c9d20094108d23984deb1af56dd730166bd8 # v1.0.11
        with:
          version: ${{steps.version.outputs.version}}
      - name: Create release
        uses: conventional-actions/create-release@50cd05b8ea9f2f3f32bbb822706b01ebf2ccce62 # v1.0.29
        with:
          tag_name: ${{steps.version.outputs.version}}
      - name: Create major release
        uses: conventional-actions/create-release@50cd05b8ea9f2f3f32bbb822706b01ebf2ccce62 # v1.0.29
        with:
          tag_name: ${{steps.version.outputs.version-major}}
      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24
          cache: 'npm'
          scope: conventional-actions
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run all
      - name: Publish
        run: npm publish --access public

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  packages: write
